# Generated by Django 3.2.13 on 2022-05-03 04:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='showtime',
            name='max_seats',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie_id',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
