# Generated by Django 3.2.13 on 2022-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220503_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie_details',
            field=models.JSONField(null=True),
        ),
    ]
