# Generated by Django 3.2.13 on 2022-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_showtime_movie_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_seats',
            field=models.IntegerField(default=1),
        ),
    ]
